repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      args: ["--skip", "*.html, ./static/", "-L", "nam"]
  - repo: local
    hooks:
    - id: check-post-names
      name: check-post-names
      entry: python scripts/check_post_names.py
      language: python
      additional_dependencies:
        - python-slugify
