[project]
name = "hugo-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "linkchecker>=10.5.0",
    "pre-commit>=4.2.0",
]
