name: Google Indexing
on:
    push:
        branches:
        - master
        paths:
        - 'content/**'
jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - uses: robingenz/action-google-indexing@v1.0.0
        with:
          siteUrl: 'https://www.aazuspan.dev'
          gcpServiceAccountKey: ${{ secrets.SERVICE_KEY }}